csv_columns = ["volume_id",
            "book_id",
            "chapter_id",
            "verse_id",
            "volume_title",
            "book_title",
            "volume_long_title",
            "book_long_title",
            "volume_subtitle",
            "book_subtitle",
            "volume_short_title",
            "book_short_title",
            "volume_lds_url",
            "book_lds_url",
            "chapter_number",
            "verse_number",
            "verse_title",
            "verse_short_title"]

csv_simplified_columns = ["volume_title",
                          "book_title",
                          "chapter_number",
                          "verse_number",
                          "verse_title"]